### ISSUE TITLE
help convert question

### ISSUE THREAD

**Issue by github5588** [neolord0/hwplib#56]
this **HWPFile** object ,can be converted to DOC?

**Comment by neolord0** [comment]
HWP and MS-WORD are a kind of word processor. So, in theory, the HWP file can be converted to a doc file. But, they do not match one-on-one functionally.  You have to choose which MS-WORD function to convert the HWP's. This is difficult because you have to know them all. If you overcome this difficulty, you will get similar results with eyes.
